### ISSUE TITLE
warnings and incomplete downloads

### ISSUE THREAD

**Issue by vincent-de-jong** [phoggren/digitalocean-ddns#1]
Hi,
I'm still a newbie, so I might get this wrong, but it seems that the code isn't downloading/deploying properly.
Below is a copy of my terminal output. I hope this helps.

```
root@cever-Alpha:/usr/local/lib# npm install digitalocean-ddns --global
loadDep:got → get         ▀ ╢███████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:responselike → re ▐ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:responselike → re ▄ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine cacheable-lookup@5.0.3: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine http2-wrapper@1.0.0-beta.5.2: wanted: {"node":">=10.19.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine decompress-response@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
loadDep:responselike → af ▀ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:json-buffer → fet ▄ ╢██████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:resolve-alpn → re ▄ ╢███████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
/usr/local/bin/digitalocean-ddns -> /usr/local/lib/node_modules/digitalocean-ddns/bin/digitalocean-ddns
/usr/local/bin/settings.json -> /usr/local/lib/node_modules/digitalocean-ddns/bin/settings.json
/usr/local/lib
└─┬ digitalocean-ddns@0.5.2 
  ├── dotenv@8.2.0 
  └─┬ got@11.7.0 
    ├── @sindresorhus/is@3.1.2 
    ├─┬ @szmarczak/http-timer@4.0.5 
    │ └── defer-to-connect@2.0.0 
    ├─┬ @types/cacheable-request@6.0.1 
    │ ├── @types/http-cache-semantics@4.0.0 
    │ ├── @types/keyv@3.1.1 
    │ └── @types/node@14.11.2 
    ├── @types/responselike@1.0.0 
    ├── cacheable-lookup@5.0.3 
    ├─┬ cacheable-request@7.0.1 
    │ ├─┬ clone-response@1.0.2 
    │ │ └── mimic-response@1.0.1 
    │ ├─┬ get-stream@5.2.0 
    │ │ └─┬ pump@3.0.0 
    │ │   ├── end-of-stream@1.4.4 
    │ │   └─┬ once@1.4.0 
    │ │     └── wrappy@1.0.2 
    │ ├── http-cache-semantics@4.1.0 
    │ ├─┬ keyv@4.0.3 
    │ │ └── json-buffer@3.0.1 
    │ └── normalize-url@4.5.0 
    ├─┬ decompress-response@6.0.0 
    │ └── mimic-response@3.1.0 
    ├─┬ http2-wrapper@1.0.0-beta.5.2 
    │ ├── quick-lru@5.1.1 
    │ └── resolve-alpn@1.0.0 
    ├── lowercase-keys@2.0.0 
    ├── p-cancelable@2.0.0 
    └── responselike@2.0.0 

root@cever-Alpha:/usr/local/lib# digitalocean-ddns --dns-records
/usr/local/lib/node_modules/digitalocean-ddns/node_modules/got/dist/source/create.js:157
    const paginateEach = (async function* (url, options) {
                                        ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/digitalocean-ddns/node_modules/got/dist/source/index.js:14:18)


```

**Comment by hoggren** [comment]
What version of NodeJS are you using? Run `node -v` in a terminal. I would guess it's quite old 🌈

**Comment by vincent-de-jong** [comment]
Hi Patrick,

I was unaware I needed nodeJS, so that will most likely be the problem.
(I'm very new at programming/networks/linux so my apologies for that).
Thank you for your advice

Cheers,
Vincent

**Comment by hoggren** [comment]
Thats okey, glad I could help!
